#!/bin/bash
#
# @file       update_mirrorlist
# @author     Chirantan Ekbote (chirantan.ekbote <at> gmail.com)
# @date       2012-10-23
# @version    0.2
# @brief      Weekly update of the pacman mirrorlist
#

#unset PATH  # suggestion from H. Milz: avoid accidental use of $PATH

# ------------- system commands used by this script --------------------

CP=/usr/bin/cp
REFLECTOR=/usr/bin/reflector
PKGFILE=//usr/bin/pkgfile
PACMAN=/usr/bin/pacman

# ------------- file locations -----------------------------------------

MIRRORLIST=/etc/pacman.d/mirrorlist
BACKUP=/etc/pacman.d/mirrorlist.backup

# ------------- the script itself --------------------------------------

# Back up the mirror list
$CP $MIRRORLIST $BACKUP

# Generate the new list
$REFLECTOR --latest 80 --sort score --fastest 40 --save $MIRRORLIST

# Update the pacman databases
$PACMAN -Syy

# Update the command-not-found database
$PKGFILE --update
